apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    tier: {{ .Values.frontend.labels.tier }}
    app: {{ .Values.frontend.labels.app }}


spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      tier: {{ .Values.frontend.labels.tier }}
      app: {{ .Values.frontend.labels.app }}
  template:
    metadata:
      name: {{ .Values.frontend.name }}
      labels:
        tier: {{ .Values.frontend.labels.tier }}
        app: {{ .Values.frontend.labels.app }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
          - containerPort: {{ .Values.frontend.service.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    tier: {{ .Values.backend.labels.tier }}
    app: {{ .Values.backend.labels.app }}


spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      tier: {{ .Values.backend.labels.tier }}
      app: {{ .Values.backend.labels.app }}
  template:
    metadata:
      name: {{ .Values.backend.name }}
      labels:
        tier: {{ .Values.backend.labels.tier }}
        app: {{ .Values.backend.labels.app }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
          - containerPort: {{ .Values.backend.service.port }}