apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.frontend.service.name }}
spec:
  selector:
    tier: {{ .Values.frontend.labels.tier }}
    app: {{ .Values.frontend.labels.app }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    nodePort: {{ .Values.frontend.service.nodePort }}
  type: {{ .Values.frontend.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.backend.service.name }}
spec:
  selector:
    tier: {{ .Values.backend.labels.tier }}
    app: {{ .Values.backend.labels.app }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: {{ .Values.backend.service.type }}
