name: hello

on:
  push:
    branches:
      - main
      - develop

jobs:
  job1:
    runs-on: local
    steps:
      - name: first
        uses: actions/checkout@c4
      - name: message
        uses: echo "Hi"

